# Generated by Django 5.0.6 on 2024-08-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=150)),
                ('unidadMedida', models.CharField(max_length=150)),
                ('stock', models.IntegerField(null=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('idEntrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('unidadMedida', models.CharField(max_length=150)),
                ('observacion', models.CharField(max_length=150)),
                ('cantidadEntrada', models.IntegerField()),
                ('valorUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('idSalida', models.BigAutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=150)),
                ('observacion', models.CharField(max_length=150)),
                ('cantidadSalida', models.IntegerField()),
                ('valorUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='StockInventadrios',
            fields=[
                ('idStockInventadrio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
                ('unidadMedida', models.CharField(max_length=150)),
                ('stock', models.IntegerField()),
                ('valorUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('valorInvenario', models.IntegerField()),
                ('idEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.entradas')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('idSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.salidas')),
            ],
        ),
    ]
