# Generated by Django 5.0.7 on 2024-09-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=150)),
                ('unidadMedida', models.CharField(default='sin unidad de medida', max_length=150)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('idEntrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaEnt', models.DateField()),
                ('unidadMedida', models.CharField(default=0, max_length=150)),
                ('observacion', models.CharField(default=0, max_length=150)),
                ('cantidadEntrada', models.IntegerField(default=0)),
                ('valorUnidad', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('idSalida', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaSal', models.DateField()),
                ('documento', models.CharField(max_length=150)),
                ('observacion', models.CharField(default='sin Observacion', max_length=150)),
                ('cantidadSalida', models.IntegerField(default=0)),
                ('valorUnidad', models.IntegerField(default=0)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='StockInventarios',
            fields=[
                ('idStockInventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=150)),
                ('unidadMedida', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default=0)),
                ('valorUnidad', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('valorInvenario', models.IntegerField(default=0)),
                ('idEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.entradas')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('idSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.salidas')),
            ],
        ),
    ]
