# Generated by Django 5.0.7 on 2024-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='cantEntInicial',
            field=models.IntegerField(default=0),
        ),
    ]
