# Generated by Django 5.0.6 on 2024-08-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInventadrios',
            new_name='StockInventarios',
        ),
    ]
