# Generated by Django 5.0.7 on 2024-09-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_entradas_cantentinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas',
            name='totalValorSal',
            field=models.IntegerField(default=0),
        ),
    ]
