# Generated by Django 5.0.7 on 2024-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_stockinventadrios_stockinventarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventarios',
            name='valorUnidad',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
