# Generated by Django 5.0.7 on 2024-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_stockinventarios_valorunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='valorUnidad',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
