# Generated by Django 5.0.6 on 2024-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
