# Generated by Django 5.0.6 on 2024-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_entradas_valorunidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinventarios',
            old_name='idStockInventadrio',
            new_name='idStockInventario',
        ),
        migrations.AlterField(
            model_name='productos',
            name='idProducto',
            field=models.CharField(blank=True, max_length=150, primary_key=True, serialize=False),
        ),
    ]
