# Generated by Django 5.0.7 on 2024-08-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_idstockinventadrio_stockinventarios_idstockinventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='valorUnidad',
            field=models.IntegerField(),
        ),
    ]
