# Generated by Django 5.0.6 on 2024-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_entradas_cantidadentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
