# Generated by Django 5.0.6 on 2024-08-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='idProveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores'),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='idCliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes'),
        ),
    ]
