# Generated by Django 5.0.6 on 2024-08-28 19:08

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_entradas_idproveedor_alter_salidas_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='idProveedor',
            field=models.ForeignKey(default=inventario.models.default_proveedor, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores'),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='idCliente',
            field=models.ForeignKey(default=inventario.models.default_cliente, on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes'),
        ),
    ]
